apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
spec:
  clusterIP: 172.20.38.211
  clusterIPs:
  - 172.20.38.211
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8001
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
